using System.Net;
using Allure.Net.Commons;
using Allure.NUnit.Attributes;
using AwesomeAssertions;
using AwesomeAssertions.Execution;
using CsharpTestAutomation.Tests.Api.Clients;
using CsharpTestAutomation.Tests.Api.Dtos.Common;
using CsharpTestAutomation.Tests.Api.Dtos.Ipam;
using CsharpTestAutomation.Tests.Api.Factories;
using CsharpTestAutomation.Tests.Database.NetBox.DTO;
using CsharpTestAutomation.Tests.Database.NetBox.Queries;
using CsharpTestAutomation.Tests.Steps.Api.NetBox;
using CsharpTestAutomation.Tests.TestData.NetBox;
using RestSharp;

namespace CsharpTestAutomation.Tests.Tests.Api;

[AllureSuite("API")]
[AllureEpic("NetBox")]
[AllureFeature("IPAM - IP Address")]
public class IpAddressesApiTests : ApiTestBase
{
    private IpamApiClient IpamClient => GetClient<IpamApiClient>();

    private IpamSteps IpamSteps => new(IpamClient, ScenarioCleanupActions);

    protected override async Task OnSetUpAsync()
    {
        await base.OnSetUpAsync();
        RegisterClient(new IpamApiClient(RestClientFactory, NetBoxAuthenticator));
    }

    [Test]
    [AllureStory("Creating a IP Address returns and persists the requested fields")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_CreatedIpAddressReturnedAndPersisted_When_IpAddressIsCreated()
    {
        // Arrange
        CreatePrefixDto prefixRequest = new CreatePrefixDtoBuilder().Default().Build();
        RestResponse<PrefixDetailDto> prefixResponse = await IpamSteps.CreatePrefixAsync(prefixRequest);
        prefixResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        prefixResponse.Data.Should().NotBeNull();
        CreateIpAddressDto request = new CreateIpAddressDtoBuilder().Default()
            .With(x => x.Address = NetBoxTestData.NewIpAddress(prefixResponse.Data!.Prefix)).Build();

        // Act
        RestResponse<IpAddressDetailDto> response = await IpamSteps.CreateIpAddressAsync(request);

        // Assert
        IpAddressDetailDto created = RequireIpAddress(response, HttpStatusCode.Created);
        created.Should().BeEquivalentTo(new
        {
            request.Address,
            request.Description,
            Status = new { Value = request.Status }
        }, options => options.ExcludingMissingMembers(), "Id, Url, Display and status labels are generated by NetBox");
        RestResponse<IpAddressDetailDto> getResponse = await IpamClient.GetIpAddressAsync(created.Id);
        getResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        getResponse.Data.Should().BeEquivalentTo(created);
        AssertPersistedIpAddress(created);
    }

    [Test]
    [AllureStory("An exact CIDR filter returns only the matching IP Address")]
    [AllureSeverity(SeverityLevel.normal)]
    [AllureOwner("Automation Team")]
    public async Task Verify_MatchingIpAddressReturned_When_IpAddressIsFilteredByCidr()
    {
        // Arrange
        CreatePrefixDto prefixRequest = new CreatePrefixDtoBuilder().Default().Build();
        RestResponse<PrefixDetailDto> prefixResponse = await IpamSteps.CreatePrefixAsync(prefixRequest);
        prefixResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        prefixResponse.Data.Should().NotBeNull();
        CreateIpAddressDto request = new CreateIpAddressDtoBuilder().Default()
            .With(x => x.Address = NetBoxTestData.NewIpAddress(prefixResponse.Data!.Prefix)).Build();
        IpAddressDetailDto created = RequireIpAddress(await IpamSteps.CreateIpAddressAsync(request), HttpStatusCode.Created);

        // Act
        RestResponse<PagedResultDto<IpAddressDetailDto>> response = await IpamClient.FindIpAddressesByAddressAsync(request.Address);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Data.Should().NotBeNull();
        response.Data!.Count.Should().Be(1);
        response.Data.Results.Should().ContainSingle().Which.Should().BeEquivalentTo(created);
    }

    [Test]
    [AllureStory("An active IP Address can be reserved without changing its CIDR")]
    [AllureSeverity(SeverityLevel.normal)]
    [AllureOwner("Automation Team")]
    public async Task Verify_ReservedStatusPersisted_When_ActiveIpAddressIsUpdated()
    {
        // Arrange
        CreatePrefixDto prefixRequest = new CreatePrefixDtoBuilder().Default().Build();
        RestResponse<PrefixDetailDto> prefixResponse = await IpamSteps.CreatePrefixAsync(prefixRequest);
        prefixResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        prefixResponse.Data.Should().NotBeNull();
        CreateIpAddressDto request = new CreateIpAddressDtoBuilder().Default()
            .With(x => x.Address = NetBoxTestData.NewIpAddress(prefixResponse.Data!.Prefix)).Build();
        IpAddressDetailDto created = RequireIpAddress(await IpamSteps.CreateIpAddressAsync(request), HttpStatusCode.Created);
        created.Status.Value.Should().Be(NetBoxTestData.ActiveStatus);
        UpdateIpAddressDto update = new UpdateIpAddressDtoBuilder().Default().Build();

        // Act
        RestResponse<IpAddressDetailDto> response = await IpamClient.UpdateIpAddressAsync(created.Id, update);

        // Assert
        IpAddressDetailDto updated = RequireIpAddress(response, HttpStatusCode.OK);
        using (new AssertionScope())
        {
            updated.Status.Value.Should().Be(NetBoxTestData.ReservedStatus);
            updated.Status.Label.Should().Be("Reserved");
            updated.Should().BeEquivalentTo(created with
            {
                Status = new StatusFieldDto { Value = update.Status, Label = "Reserved" },
                Description = update.Description
            });
        }

        RestResponse<IpAddressDetailDto> getResponse = await IpamClient.GetIpAddressAsync(created.Id);
        getResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        getResponse.Data.Should().BeEquivalentTo(updated);
        AssertPersistedIpAddress(updated);
    }

    [Test]
    [AllureStory("Deleting a IP Address removes it from REST and PostgreSQL")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_IpAddressRemovedAcrossLayers_When_IpAddressIsDeleted()
    {
        // Arrange
        CreatePrefixDto prefixRequest = new CreatePrefixDtoBuilder().Default().Build();
        RestResponse<PrefixDetailDto> prefixResponse = await IpamSteps.CreatePrefixAsync(prefixRequest);
        prefixResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        prefixResponse.Data.Should().NotBeNull();
        CreateIpAddressDto request = new CreateIpAddressDtoBuilder().Default()
            .With(x => x.Address = NetBoxTestData.NewIpAddress(prefixResponse.Data!.Prefix)).Build();
        IpAddressDetailDto created = RequireIpAddress(await IpamSteps.CreateIpAddressAsync(request), HttpStatusCode.Created);

        // Act
        RestResponse response = await IpamClient.DeleteIpAddressAsync(created.Id);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NoContent);
        RestResponse<IpAddressDetailDto> getResponse = await IpamClient.GetIpAddressAsync(created.Id);
        using (new AssertionScope())
        {
            getResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
            IpamDatabaseRepository.GetIpAddressByAddress(request.Address).Should().BeNull();
        }
    }

    private static IpAddressDetailDto RequireIpAddress(RestResponse<IpAddressDetailDto> response, HttpStatusCode expectedStatus)
    {
        response.StatusCode.Should().Be(expectedStatus);
        response.Data.Should().NotBeNull();
        response.Data!.Id.Should().BePositive();
        return response.Data;
    }

    private static void AssertPersistedIpAddress(IpAddressDetailDto actual)
    {
        IpAddressRowDto? row = IpamDatabaseRepository.GetIpAddressByAddress(actual.Address);
        row.Should().NotBeNull();
        row.Should().BeEquivalentTo(new IpAddressRowDto
        {
            Id = actual.Id,
            Address = actual.Address,
            Status = actual.Status.Value,
            Description = actual.Description
        }, "all represented persisted fields must match; Url, Display and status labels are derived");
    }
}
