using System.Net;
using Allure.Net.Commons;
using Allure.NUnit.Attributes;
using AwesomeAssertions;
using AwesomeAssertions.Execution;
using CsharpTestAutomation.Tests.Api.Clients;
using CsharpTestAutomation.Tests.Api.Dtos.Common;
using CsharpTestAutomation.Tests.Api.Dtos.Ipam;
using CsharpTestAutomation.Tests.Api.Factories;
using CsharpTestAutomation.Tests.Database.NetBox.DTO;
using CsharpTestAutomation.Tests.Database.NetBox.Queries;
using CsharpTestAutomation.Tests.Steps.Api.NetBox;
using CsharpTestAutomation.Tests.TestData.NetBox;
using RestSharp;

namespace CsharpTestAutomation.Tests.Tests.Api;

[AllureSuite("API")]
[AllureEpic("NetBox")]
[AllureFeature("IPAM - Prefix")]
public class PrefixesApiTests : ApiTestBase
{
    private IpamApiClient IpamClient => GetClient<IpamApiClient>();

    private IpamSteps IpamSteps => new(IpamClient, ScenarioCleanupActions);

    protected override async Task OnSetUpAsync()
    {
        await base.OnSetUpAsync();
        RegisterClient(new IpamApiClient(RestClientFactory, NetBoxAuthenticator));
    }

    [Test]
    [AllureStory("Creating a Prefix returns and persists the requested fields")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_CreatedPrefixReturnedAndPersisted_When_PrefixIsCreated()
    {
        // Arrange
        CreatePrefixDto request = new CreatePrefixDtoBuilder().Default().Build();

        // Act
        RestResponse<PrefixDto> response = await IpamSteps.CreatePrefixAsync(request);

        // Assert
        PrefixDto created = RequirePrefix(response, HttpStatusCode.Created);
        created.Should().BeEquivalentTo(new
        {
            request.Prefix,
            request.Description,
            Status = new { Value = request.Status }
        }, options => options.ExcludingMissingMembers(), "Id, Url, Display and status labels are generated by NetBox");
        RestResponse<PrefixDto> getResponse = await IpamClient.GetPrefixAsync(created.Id);
        getResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        getResponse.Data.Should().BeEquivalentTo(created);
        AssertPersistedPrefix(created);
    }

    [Test]
    [AllureStory("An exact CIDR filter returns only the matching Prefix")]
    [AllureSeverity(SeverityLevel.normal)]
    [AllureOwner("Automation Team")]
    public async Task Verify_MatchingPrefixReturned_When_PrefixIsFilteredByCidr()
    {
        // Arrange
        CreatePrefixDto request = new CreatePrefixDtoBuilder().Default().Build();
        PrefixDto created = RequirePrefix(await IpamSteps.CreatePrefixAsync(request), HttpStatusCode.Created);

        // Act
        RestResponse<PagedResultDto<PrefixDto>> response = await IpamClient.FindPrefixesByCidrAsync(request.Prefix);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Data.Should().NotBeNull();
        response.Data!.Count.Should().Be(1);
        response.Data.Results.Should().ContainSingle().Which.Should().BeEquivalentTo(created);
    }

    [Test]
    [AllureStory("An active Prefix can be reserved without changing its CIDR")]
    [AllureSeverity(SeverityLevel.normal)]
    [AllureOwner("Automation Team")]
    public async Task Verify_ReservedStatusPersisted_When_ActivePrefixIsUpdated()
    {
        // Arrange
        CreatePrefixDto request = new CreatePrefixDtoBuilder().Default().Build();
        PrefixDto created = RequirePrefix(await IpamSteps.CreatePrefixAsync(request), HttpStatusCode.Created);
        created.Status.Value.Should().Be(NetBoxTestData.ActiveStatus);
        UpdatePrefixDto update = new UpdatePrefixDtoBuilder().Default().Build();

        // Act
        RestResponse<PrefixDto> response = await IpamClient.UpdatePrefixAsync(created.Id, update);

        // Assert
        PrefixDto updated = RequirePrefix(response, HttpStatusCode.OK);
        using (new AssertionScope())
        {
            updated.Status.Value.Should().Be(NetBoxTestData.ReservedStatus);
            updated.Status.Label.Should().Be("Reserved");
            updated.Should().BeEquivalentTo(created with
            {
                Status = new StatusFieldDto { Value = update.Status, Label = "Reserved" },
                Description = update.Description
            });
        }

        RestResponse<PrefixDto> getResponse = await IpamClient.GetPrefixAsync(created.Id);
        getResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        getResponse.Data.Should().BeEquivalentTo(updated);
        AssertPersistedPrefix(updated);
    }

    [Test]
    [AllureStory("Deleting a Prefix removes it from REST and PostgreSQL")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_PrefixRemovedAcrossLayers_When_PrefixIsDeleted()
    {
        // Arrange
        CreatePrefixDto request = new CreatePrefixDtoBuilder().Default().Build();
        PrefixDto created = RequirePrefix(await IpamSteps.CreatePrefixAsync(request), HttpStatusCode.Created);

        // Act
        RestResponse response = await IpamClient.DeletePrefixAsync(created.Id);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NoContent);
        RestResponse<PrefixDto> getResponse = await IpamClient.GetPrefixAsync(created.Id);
        using (new AssertionScope())
        {
            getResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
            IpamDatabaseRepository.GetPrefixByCidr(request.Prefix).Should().BeNull();
        }
    }

    private static PrefixDto RequirePrefix(RestResponse<PrefixDto> response, HttpStatusCode expectedStatus)
    {
        response.StatusCode.Should().Be(expectedStatus);
        response.Data.Should().NotBeNull();
        response.Data!.Id.Should().BePositive();
        return response.Data;
    }

    private static void AssertPersistedPrefix(PrefixDto actual)
    {
        PrefixRowDto? row = IpamDatabaseRepository.GetPrefixByCidr(actual.Prefix);
        row.Should().NotBeNull();
        row.Should().BeEquivalentTo(new PrefixRowDto
        {
            Id = actual.Id,
            Prefix = actual.Prefix,
            Status = actual.Status.Value,
            Description = actual.Description
        }, "all represented persisted fields must match; Url, Display and status labels are derived");
    }
}
