using System.Net;
using AwesomeAssertions;
using CsharpTestAutomation.Bdd.Tests.Api.Clients;
using CsharpTestAutomation.Bdd.Tests.Api.Dtos.Common;
using CsharpTestAutomation.Bdd.Tests.Api.Dtos.Devices;
using CsharpTestAutomation.Bdd.Tests.Context;
using CsharpTestAutomation.Bdd.Tests.Steps.Api.NetBox;
using CsharpTestAutomation.Bdd.Tests.UI.Pages;
using CsharpTestAutomation.Bdd.Tests.UI.Pages.NetBox;
using CsharpTestAutomation.Framework.Common;
using Microsoft.Playwright;
using Reqnroll;
using RestSharp;
using static Microsoft.Playwright.Assertions;

namespace CsharpTestAutomation.Bdd.Tests.Steps.UI.NetBox;

[Binding]
[Scope(Tag = "Device")]
public sealed class DeviceUiSteps(IPage page, DevicesApiClient client, ScenarioCleanupActions cleanup, DeviceScenarioState state)
{
    [When("the Device is created in the web application")]
    public async Task CreateAsync()
    {
        CreateDeviceDto request = state.CreateRequest;
        RegisterUiDeviceCleanup(request.Name, request.Site);
        DevicesListPage list = BaseUIPage.Create<DevicesListPage>(page);
        await list.NavigateAsync();
        DeviceEditPage edit = await list.AddDeviceAsync();
        DevicePrerequisites prerequisites = state.Prerequisites;
        state.DetailsPage = await edit.CreateDeviceAsync(request,
            prerequisites.Site.Name, prerequisites.DeviceType.Model, prerequisites.Role.Name);
    }

    [Then("the requested Device details are displayed and retrievable")]
    public async Task VerifyCreationAsync()
    {
        CreateDeviceDto request = state.CreateRequest;
        DevicePrerequisites prerequisites = state.Prerequisites;
        await Expect(state.DetailsPage.NameHeading(request.Name)).ToBeVisibleAsync();
        await Expect(state.DetailsPage.SiteLink(prerequisites.Site.Name)).ToBeVisibleAsync();
        await Expect(state.DetailsPage.DeviceTypeLink(prerequisites.DeviceType.Model)).ToBeVisibleAsync();
        await Expect(state.DetailsPage.RoleLink(prerequisites.Role.Name)).ToBeVisibleAsync();
        await Expect(state.DetailsPage.Status).ToHaveTextAsync(request.Status, new() { IgnoreCase = true });
        await Expect(state.DetailsPage.Description).ToHaveTextAsync(request.Description);

        RestResponse<PagedResultDto<DeviceDetailDto>> response = await client.FindDevicesByNameAsync(request.Name);
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Data.Should().NotBeNull();
        response.Data!.Count.Should().Be(1);
        DeviceDetailDto device = response.Data.Results.Should().ContainSingle().Which;
        device.Id.Should().BePositive();
        device.Should().BeEquivalentTo(new
        {
            request.Name,
            request.Description,
            Site = new { Id = request.Site, prerequisites.Site.Name, prerequisites.Site.Slug },
            DeviceType = new { Id = request.DeviceType, prerequisites.DeviceType.Model, prerequisites.DeviceType.Slug },
            Role = new { Id = request.Role, prerequisites.Role.Name, prerequisites.Role.Slug },
            Status = new { Value = request.Status }
        }, options => options.ExcludingMissingMembers(), "Id, Url, Display and nested display labels are generated by NetBox");
        state.PersistedDevice = device;
    }

    // Register before submission and restrict deletion to the scenario's unique name and owned Site.
    private void RegisterUiDeviceCleanup(string name, int siteId) => cleanup.AddCleanUpAction(async () =>
    {
        RestResponse<PagedResultDto<DeviceDetailDto>> response = await client.FindDevicesByNameAsync(name);
        if (response.StatusCode != HttpStatusCode.OK || response.Data is null)
        {
            throw new InvalidOperationException($"Could not find the UI-created device for cleanup: {response.StatusCode} ({response.ResponseStatus}).");
        }

        foreach (DeviceDetailDto device in response.Data.Results.Where(x => x.Name == name && x.Site.Id == siteId))
        {
            await DeviceApiSteps.DeleteOwnedAsync(() => client.DeleteDeviceAsync(device.Id), "device", device.Id);
        }
    });
}
