using System.Net;
using Allure.Net.Commons;
using Allure.NUnit.Attributes;
using AwesomeAssertions;
using CsharpTestAutomation.Tests.Api.Clients;
using CsharpTestAutomation.Tests.Api.Dtos.Common;
using CsharpTestAutomation.Tests.Api.Dtos.Devices;
using CsharpTestAutomation.Tests.Api.Factories;
using CsharpTestAutomation.Tests.Database.NetBox.DTO;
using CsharpTestAutomation.Tests.Database.NetBox.Queries;
using CsharpTestAutomation.Tests.Steps.Api.NetBox;
using CsharpTestAutomation.Tests.UI.Pages.NetBox;
using RestSharp;
using static Microsoft.Playwright.Assertions;

namespace CsharpTestAutomation.Tests.Tests.UI.NetBox;

[AllureSuite("UI")]
[AllureEpic("NetBox")]
[AllureFeature("Device Management")]
public class DeviceManagementUiTests : NetBoxUiTestBase
{
    private DevicesApiClient DevicesClient => GetClient<DevicesApiClient>();

    private DeviceSteps DeviceSteps => new(
        GetClient<ManufacturersApiClient>(), GetClient<DeviceTypesApiClient>(),
        GetClient<DeviceRolesApiClient>(), GetClient<SitesApiClient>(), DevicesClient, ScenarioCleanupActions);

    protected override async Task OnSetUpAsync()
    {
        await base.OnSetUpAsync();
        RegisterClient(new ManufacturersApiClient(RestClientFactory, NetBoxAuthenticator));
        RegisterClient(new DeviceTypesApiClient(RestClientFactory, NetBoxAuthenticator));
        RegisterClient(new DeviceRolesApiClient(RestClientFactory, NetBoxAuthenticator));
        RegisterClient(new SitesApiClient(RestClientFactory, NetBoxAuthenticator));
        RegisterClient(new DevicesApiClient(RestClientFactory, NetBoxAuthenticator));
    }

    [Test]
    [AllureStory("Creating a Device through the UI persists its fields across REST API and PostgreSQL")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_DevicePersistedAcrossLayers_When_DeviceIsCreatedThroughUi()
    {
        // Arrange
        DevicePrerequisites prerequisites = await DeviceSteps.CreatePrerequisitesAsync();
        CreateDeviceDto request = new CreateDeviceDtoBuilder().Default()
            .With(x => x.DeviceType = prerequisites.DeviceType.Id)
            .With(x => x.Role = prerequisites.Role.Id)
            .With(x => x.Site = prerequisites.Site.Id).Build();
        DeviceSteps.RegisterUiDeviceCleanup(request.Name, request.Site);

        // Act
        DevicesListPage listPage = GetPage<DevicesListPage>();
        await listPage.NavigateAsync();
        DeviceEditPage editPage = await listPage.AddDeviceAsync();
        DeviceDetailsPage detailsPage = await editPage.CreateDeviceAsync(
            request, prerequisites.Site.Name, prerequisites.DeviceType.Model, prerequisites.Role.Name);

        // Assert
        using (Assert.EnterMultipleScope())
        {
            await Expect(detailsPage.NameHeading(request.Name)).ToBeVisibleAsync();
            await Expect(detailsPage.SiteLink(prerequisites.Site.Name)).ToBeVisibleAsync();
            await Expect(detailsPage.DeviceTypeLink(prerequisites.DeviceType.Model)).ToBeVisibleAsync();
            await Expect(detailsPage.RoleLink(prerequisites.Role.Name)).ToBeVisibleAsync();
            await Expect(detailsPage.Status).ToHaveTextAsync(request.Status, new() { IgnoreCase = true });
            await Expect(detailsPage.Description).ToHaveTextAsync(request.Description);
        }

        RestResponse<PagedResultDto<DeviceDetailDto>> response = await DevicesClient.FindDevicesByNameAsync(request.Name);
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Data.Should().NotBeNull();
        response.Data!.Count.Should().Be(1);
        DeviceDetailDto device = response.Data.Results.Should().ContainSingle().Which;
        device.Id.Should().BePositive();
        device.Should().BeEquivalentTo(new
        {
            request.Name,
            request.Description,
            Site = new { Id = request.Site, prerequisites.Site.Name, prerequisites.Site.Slug },
            DeviceType = new { Id = request.DeviceType, prerequisites.DeviceType.Model, prerequisites.DeviceType.Slug },
            Role = new { Id = request.Role, prerequisites.Role.Name, prerequisites.Role.Slug },
            Status = new { Value = request.Status }
        }, options => options.ExcludingMissingMembers(), "Id, Url, Display and nested display labels are generated by NetBox");

        DeviceRowDto? row = DevicesDatabaseRepository.GetByName(request.Name);
        row.Should().NotBeNull();
        row.Should().BeEquivalentTo(new DeviceRowDto
        {
            Id = device.Id,
            Name = request.Name,
            SiteId = request.Site,
            DeviceTypeId = request.DeviceType,
            RoleId = request.Role,
            Status = request.Status,
            Description = request.Description
        }, "all persisted Device fields represented by the API DTO must match; Url and display labels are derived");
    }
}
