using System.Net;
using Allure.Net.Commons;
using Allure.NUnit.Attributes;
using AwesomeAssertions;
using CsharpTestAutomation.Tests.Api.Clients;
using CsharpTestAutomation.Tests.Api.Dtos.Common;
using CsharpTestAutomation.Tests.Api.Dtos.Ipam;
using CsharpTestAutomation.Tests.Api.Factories;
using CsharpTestAutomation.Tests.Database.NetBox.DTO;
using CsharpTestAutomation.Tests.Database.NetBox.Queries;
using CsharpTestAutomation.Tests.Steps.Api.NetBox;
using CsharpTestAutomation.Tests.TestData.NetBox;
using CsharpTestAutomation.Tests.UI.Pages.NetBox;
using RestSharp;
using static Microsoft.Playwright.Assertions;

namespace CsharpTestAutomation.Tests.Tests.UI.NetBox;

[AllureSuite("UI")]
[AllureEpic("NetBox")]
[AllureFeature("IPAM - Prefix")]
public class IpamManagementUiTests : NetBoxUiTestBase
{
    private IpamApiClient IpamClient => GetClient<IpamApiClient>();

    private IpamSteps IpamSteps => new(IpamClient, ScenarioCleanupActions);

    protected override async Task OnSetUpAsync()
    {
        await base.OnSetUpAsync();
        RegisterClient(new IpamApiClient(RestClientFactory, NetBoxAuthenticator));
    }

    [Test]
    [AllureStory("Creating a Prefix through the UI persists it across REST API and PostgreSQL")]
    [AllureSeverity(SeverityLevel.critical)]
    [AllureOwner("Automation Team")]
    public async Task Verify_PrefixPersistedAcrossLayers_When_PrefixIsCreatedThroughUi()
    {
        // Arrange
        CreatePrefixDto request = new CreatePrefixDtoBuilder().Default()
            .With(x => x.Description = NetBoxTestData.NewName("prefix")).Build();
        IpamSteps.RegisterUiPrefixCleanup(request);

        // Act
        PrefixesPage listPage = GetPage<PrefixesPage>();
        await listPage.NavigateAsync();
        PrefixEditPage editPage = await listPage.AddPrefixAsync();
        PrefixDetailsPage detailsPage = await editPage.CreatePrefixAsync(request);
        RestResponse<PagedResultDto<PrefixDetailDto>> response = await IpamClient.FindPrefixesByCidrAsync(request.Prefix, request.Description);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Data.Should().NotBeNull();
        PrefixDetailDto prefix = response.Data!.Results.Should().ContainSingle(x => x.Description == request.Description).Which;
        IpamSteps.RegisterPrefixCleanup(prefix.Id);
        response.Data.Count.Should().Be(1);
        prefix.Id.Should().BePositive();

        await Expect(detailsPage.PrefixHeading(request.Prefix)).ToBeVisibleAsync();
        await Expect(detailsPage.Status).ToHaveTextAsync(request.Status, new() { IgnoreCase = true });
        await Expect(detailsPage.Description).ToHaveTextAsync(request.Description);
        prefix.Should().BeEquivalentTo(new
        {
            request.Prefix,
            request.Description,
            Status = new { Value = request.Status }
        }, options => options.ExcludingMissingMembers(), "Id, Url, Display and status labels are generated by NetBox");

        PrefixRowDto? row = IpamDatabaseRepository.GetPrefixByCidr(request.Prefix);
        row.Should().NotBeNull();
        row.Should().BeEquivalentTo(new PrefixRowDto
        {
            Id = prefix.Id,
            Prefix = request.Prefix,
            Status = request.Status,
            Description = request.Description
        }, "all represented persisted Prefix fields must match; Url, Display and status labels are derived");
    }
}
